---
- name: Ensure nfs volume exists
  file:
    path: "{{ nfs_share }}"
    state: directory
  when:
    - enable_nfs | bool
    - inventory_hostname in groups['storage']

- name: Copy nfs exportfs for nfs-servers
  template:
    src: exports.j2
    dest: /etc/exports
  when:
    - enable_nfs | bool
    - inventory_hostname in groups['storage']
  notify:
    - Restart nfs service

# Check service, start it if the status is not active.
- name: Check nfs servers service status
  service_check:
    service_name: "{{ item.name }}"
    service_type: "systemd"
  when:
    - enable_nfs | bool
    - inventory_hostname in groups['storage']
    - ansible_distribution == item.os
  loop:
    - {name: nfs, os: CentOS}
    - {name: nfs-kernel-server, os: Ubuntu}
    - {name: rpcbind, os: CentOS}
    - {name: rpcbind, os: Ubuntu}
    - {name: rpcbind, os: openEuler}
  notify:
    - Restart nfs service
