---
- hosts: kube-master
  tasks:
    - name: Ensure .kube folder exist
      file:
        path: ~/.kube
        state: directory

    - name: Copy admin.conf to into ~/.kube/
      copy:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        remote_src: yes
        mode: '0600'

    - name: Install bash-completion package
      package:
        name: bash-completion
        state: present

    - name: Configure kubectl auto-completion
      lineinfile:
        path: ~/.bashrc
        line: 'source <(kubectl completion bash)'
        state: present
        create: true
        insertafter: EOF
        backup: yes
