---
- name: Restart docker service
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Restart cri-docker.service service
  service:
    name: cri-docker.service
    state: restarted
    enabled: yes

- name: Restart cri-docker.socket service
  service:
    name: cri-docker.socket
    state: restarted
    enabled: yes

- name: Restart containerd service
  service:
    name: containerd
    state: restarted
    enabled: yes

- name: Restart NetworkManager service
  service:
    name: NetworkManager
    state: restarted
    enabled: yes
